### PR TITLE
Added 'Sort by sender' option

### PR DESCRIPTION
**Pull request by boserup**
Optional, enable in preferences.

### CODE REVIEW

**Comment by boserup** [comment]
image

image

**Comment by emilstahl** [comment]
Awesome! 💪👍

**Comment by olegam** [comment]
This is great! A few comments I think we need to address:
- We need some sort of migration path when users turn on/off the option so you don't end up with a mix of the old and the new structure. I suggest we clear the folder and do a fresh sync. We should probably ask the user first with an alert so we don't accidentally delete files.
- It should not be possible to turn on/off the option while a sync is running. I suggest we bind the checkbox' enabled property in the same way as the change directory button's enabled property.

**Comment by olegam** [comment]
What do you think about the migration and change-while-syncing protection?

**Comment by boserup** [comment]
Your points are valid, I will take a look at it. I might however not be able to finish the implementation this month.

**Pull request closed without merging**
