### PR TITLE
Support for Swedish E-boks

### PR DESCRIPTION
**Pull request by sebreh**
Basic auth working, but no UI support and no saving the nationality to the Keychain. Will keep working on this PR to add this, or feel free to merge and add it yourself if you want.

### CODE REVIEW

**Comment by olegam** [comment]
Great to see this coming together

**Comment by sebreh** [comment]
@olegam this should basically be working now. Not too familiar with AppKit, but added a dropdown to select nationality when adding an account. Also added Swedish localization.

**Comment by sebreh** [comment]
Also seems do download documents from my Swedish account fine.

**Comment by olegam** [comment]
This is great! Will be included in next build

**Comment by sebreh** [comment]
:+1:

**Pull request merged**
